0 0 * * * ~/aws/access/all/allow-ad/all-allow-ad-00.sh
0 1 * * * ~/aws/access/all/allow-ad/all-allow-ad-01.sh
0 2 * * * ~/aws/access/all/allow-ad/all-allow-ad-02.sh
0 3 * * * ~/aws/access/all/allow-ad/all-allow-ad-03.sh
0 4 * * * ~/aws/access/all/allow-ad/all-allow-ad-04.sh
0 5 * * * ~/aws/access/all/allow-ad/all-allow-ad-05.sh
0 6 * * * ~/aws/access/all/allow-ad/all-allow-ad-06.sh
0 7 * * * ~/aws/access/all/allow-ad/all-allow-ad-07.sh
0 8 * * * ~/aws/access/all/allow-ad/all-allow-ad-08.sh
0 9 * * * ~/aws/access/all/allow-ad/all-allow-ad-09.sh
0 10 * * * ~/aws/access/all/allow-ad/all-allow-ad-10.sh
0 11 * * * ~/aws/access/all/allow-ad/all-allow-ad-11.sh
0 12 * * * ~/aws/access/all/allow-ad/all-allow-ad-12.sh
0 13 * * * ~/aws/access/all/allow-ad/all-allow-ad-13.sh
0 14 * * * ~/aws/access/all/allow-ad/all-allow-ad-14.sh
0 15 * * * ~/aws/access/all/allow-ad/all-allow-ad-15.sh
0 16 * * * ~/aws/access/all/allow-ad/all-allow-ad-16.sh
0 17 * * * ~/aws/access/all/allow-ad/all-allow-ad-17.sh
0 18 * * * ~/aws/access/all/allow-ad/all-allow-ad-18.sh
0 19 * * * ~/aws/access/all/allow-ad/all-allow-ad-19.sh
0 20 * * * ~/aws/access/all/allow-ad/all-allow-ad-20.sh
0 21 * * * ~/aws/access/all/allow-ad/all-allow-ad-21.sh
0 22 * * * ~/aws/access/all/allow-ad/all-allow-ad-22.sh
0 23 * * * ~/aws/access/all/allow-ad/all-allow-ad-23.sh
0 0 * * * ~/aws/access/all/allow-wd/all-allow-wd-00.sh
0 1 * * * ~/aws/access/all/allow-wd/all-allow-wd-01.sh
0 2 * * * ~/aws/access/all/allow-wd/all-allow-wd-02.sh
0 3 * * * ~/aws/access/all/allow-wd/all-allow-wd-03.sh
0 4 * * * ~/aws/access/all/allow-wd/all-allow-wd-04.sh
0 5 * * * ~/aws/access/all/allow-wd/all-allow-wd-05.sh
0 6 * * * ~/aws/access/all/allow-wd/all-allow-wd-06.sh
0 7 * * * ~/aws/access/all/allow-wd/all-allow-wd-07.sh
0 8 * * * ~/aws/access/all/allow-wd/all-allow-wd-08.sh
0 9 * * * ~/aws/access/all/allow-wd/all-allow-wd-09.sh
0 10 * * * ~/aws/access/all/allow-wd/all-allow-wd-10.sh
0 11 * * * ~/aws/access/all/allow-wd/all-allow-wd-11.sh
0 12 * * * ~/aws/access/all/allow-wd/all-allow-wd-12.sh
0 13 * * * ~/aws/access/all/allow-wd/all-allow-wd-13.sh
0 14 * * * ~/aws/access/all/allow-wd/all-allow-wd-14.sh
0 15 * * * ~/aws/access/all/allow-wd/all-allow-wd-15.sh
0 16 * * * ~/aws/access/all/allow-wd/all-allow-wd-16.sh
0 17 * * * ~/aws/access/all/allow-wd/all-allow-wd-17.sh
0 18 * * * ~/aws/access/all/allow-wd/all-allow-wd-18.sh
0 19 * * * ~/aws/access/all/allow-wd/all-allow-wd-19.sh
0 20 * * * ~/aws/access/all/allow-wd/all-allow-wd-20.sh
0 21 * * * ~/aws/access/all/allow-wd/all-allow-wd-21.sh
0 22 * * * ~/aws/access/all/allow-wd/all-allow-wd-22.sh
0 23 * * * ~/aws/access/all/allow-wd/all-allow-wd-23.sh
0 0 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-00.sh
0 1 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-01.sh
0 2 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-02.sh
0 3 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-03.sh
0 4 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-04.sh
0 5 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-05.sh
0 6 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-06.sh
0 7 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-07.sh
0 8 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-08.sh
0 9 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-09.sh
0 10 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-10.sh
0 11 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-11.sh
0 12 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-12.sh
0 13 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-13.sh
0 14 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-14.sh
0 15 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-15.sh
0 16 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-16.sh
0 17 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-17.sh
0 18 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-18.sh
0 19 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-19.sh
0 20 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-20.sh
0 21 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-21.sh
0 22 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-22.sh
0 23 * * * ~/aws/access/all/disallow-ad/all-disallow-ad-23.sh
0 0 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-00.sh
0 1 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-01.sh
0 2 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-02.sh
0 3 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-03.sh
0 4 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-04.sh
0 5 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-05.sh
0 6 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-06.sh
0 7 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-07.sh
0 8 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-08.sh
0 9 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-09.sh
0 10 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-10.sh
0 11 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-11.sh
0 12 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-12.sh
0 13 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-13.sh
0 14 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-14.sh
0 15 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-15.sh
0 16 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-16.sh
0 17 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-17.sh
0 18 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-18.sh
0 19 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-19.sh
0 20 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-20.sh
0 21 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-21.sh
0 22 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-22.sh
0 23 * * * ~/aws/access/all/disallow-wd/all-disallow-wd-23.sh
